# build environment
FROM node:12-alpine as build
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/
RUN yarn --silent
COPY . /usr/src/app/
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
# new
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
# make SSL
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]